// Code generated by taoctl. DO NOT EDIT.
package handler

import (
	"net/http"

	tag "backend-learning/blog/app/tag/cmd/api/internal/handler/tag"
	"backend-learning/blog/app/tag/cmd/api/internal/svc"

	"manlu.org/tao/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/tag/list",
				Handler: tag.GetTagListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
