// Code generated by taoctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "backend-learning/blog/app/user/cmd/api/internal/handler/user"
	"backend-learning/blog/app/user/cmd/api/internal/svc"

	"manlu.org/tao/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.UserLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
