filebeat.inputs:
  - type: log
    enabled: true
    json.keys_under_root: true
    json.add_error_key: true
    paths:
      - /var/lib/docker/containers/*/*-json.log

setup.template.settings:
  index.number_of_shards: 1

fields:
  log_topic: log-blog

output.kafka:
  hosts: ["127.0.0.1:9092"]
  topic: '%{[fields.log_topic]}'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  keep_alive: 10s

# ================================= Processors =================================
processors:
  - decode_json_fields:
      fields: ['@timestamp','level','content','trace','span','duration']
      target: ""
