// Code generated by taoctl. DO NOT EDIT!
// Source: reply.proto

package server

import (
	"context"

	"backend-learning/blog/app/reply/cmd/rpc/internal/logic"
	"backend-learning/blog/app/reply/cmd/rpc/internal/svc"
	"backend-learning/blog/app/reply/cmd/rpc/reply"
)

type ReplyServer struct {
	svcCtx *svc.ServiceContext
}

func NewReplyServer(svcCtx *svc.ServiceContext) *ReplyServer {
	return &ReplyServer{
		svcCtx: svcCtx,
	}
}

func (s *ReplyServer) GetReplyByArticleId(ctx context.Context, in *reply.GetReplyByArticleIdReq) (*reply.GetReplyByArticleIdResp, error) {
	l := logic.NewGetReplyByArticleIdLogic(ctx, s.svcCtx)
	return l.GetReplyByArticleId(in)
}
