// Code generated by taoctl. DO NOT EDIT!
// Source: reply.proto

package replyclient

import (
	"context"

	"backend-learning/blog/app/reply/cmd/rpc/reply"

	"google.golang.org/grpc"
	"manlu.org/tao/zrpc"
)

type (
	GetReplyByArticleIdReq  = reply.GetReplyByArticleIdReq
	GetReplyByArticleIdResp = reply.GetReplyByArticleIdResp
	ReplyModel              = reply.ReplyModel

	Reply interface {
		GetReplyByArticleId(ctx context.Context, in *GetReplyByArticleIdReq, opts ...grpc.CallOption) (*GetReplyByArticleIdResp, error)
	}

	defaultReply struct {
		cli zrpc.Client
	}
)

func NewReply(cli zrpc.Client) Reply {
	return &defaultReply{
		cli: cli,
	}
}

func (m *defaultReply) GetReplyByArticleId(ctx context.Context, in *GetReplyByArticleIdReq, opts ...grpc.CallOption) (*GetReplyByArticleIdResp, error) {
	client := reply.NewReplyClient(m.cli.Conn())
	return client.GetReplyByArticleId(ctx, in, opts...)
}
