// Code generated by taoctl. DO NOT EDIT.
package types

type UserLoginReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type UserLoginResp struct {
	Success   bool   `json:"success"`
	Message   string `json:"message"`
	Token     string `json:"token,optional"`
	ExpiredAt int64  `json:"expiredAt,optional"`
}
