// Code generated by taoctl. DO NOT EDIT!
// Source: article.proto

package server

import (
	"context"

	"backend-learning/blog/app/article/cmd/rpc/article"
	"backend-learning/blog/app/article/cmd/rpc/internal/logic"
	"backend-learning/blog/app/article/cmd/rpc/internal/svc"
)

type ArticleServer struct {
	svcCtx *svc.ServiceContext
}

func NewArticleServer(svcCtx *svc.ServiceContext) *ArticleServer {
	return &ArticleServer{
		svcCtx: svcCtx,
	}
}

//  create article
func (s *ArticleServer) CreateArticle(ctx context.Context, in *article.CreateArticleReq) (*article.CreateArticleResp, error) {
	l := logic.NewCreateArticleLogic(ctx, s.svcCtx)
	return l.CreateArticle(in)
}

func (s *ArticleServer) GetArticleList(ctx context.Context, in *article.GetArticleListReq) (*article.GetArticleListResp, error) {
	l := logic.NewGetArticleListLogic(ctx, s.svcCtx)
	return l.GetArticleList(in)
}

func (s *ArticleServer) ShowArticle(ctx context.Context, in *article.ShowArticleReq) (*article.ShowArticleResp, error) {
	l := logic.NewShowArticleLogic(ctx, s.svcCtx)
	return l.ShowArticle(in)
}

func (s *ArticleServer) DeleteArticle(ctx context.Context, in *article.DeleteArticleReq) (*article.DeleteArticleResp, error) {
	l := logic.NewDeleteArticleLogic(ctx, s.svcCtx)
	return l.DeleteArticle(in)
}
