// Code generated by taoctl. DO NOT EDIT!
// Source: tag.proto

package server

import (
	"context"

	"backend-learning/blog/app/tag/cmd/rpc/internal/logic"
	"backend-learning/blog/app/tag/cmd/rpc/internal/svc"
	"backend-learning/blog/app/tag/cmd/rpc/tag"
)

type TagServer struct {
	svcCtx *svc.ServiceContext
}

func NewTagServer(svcCtx *svc.ServiceContext) *TagServer {
	return &TagServer{
		svcCtx: svcCtx,
	}
}

func (s *TagServer) GetTagList(ctx context.Context, in *tag.GetTagListReq) (*tag.GetTagListResp, error) {
	l := logic.NewGetTagListLogic(ctx, s.svcCtx)
	return l.GetTagList(in)
}

func (s *TagServer) GetTagInfo(ctx context.Context, in *tag.GetTagInfoReq) (*tag.GetTagInfoResp, error) {
	l := logic.NewGetTagInfoLogic(ctx, s.svcCtx)
	return l.GetTagInfo(in)
}
